language:
  - cpp

sudo:
  - required

before_install:
  - sudo apt-get update -qq
  - sudo apt-get remove -qq cmake
  - sudo apt-get install -qq gcc-4.8 python2.7 nodejs
  - sudo apt-get autoremove -qq

install:
  - sh ./travis_install_cmake.sh
  - sh ./travis_install_emsdk.sh
