language:
  - cpp

sudo:
  - required

before_install:
  - sudo apt-get update -qq
  - sudo apt-get remove cmake
  - sudo apt-get install -qq python2.7 nodejs clang

install:
  - sh ./travis_install_cmake.sh
  - sh ./travis_install_emsdk.sh
